local vars = {
	Cities = T{ 
		'Norg', 
		'Western Adoulin', 
		'Lower Jeuno', 
		'Port Jeuno', 
		'Upper Jeuno',
	},
	HeroicZones = T{
		'Escha - Zi\'Tah',
		'Reisenjima',
		'Escha - Ru\'Aun',
		'Reisenjima Sanctorium',
	},
	BluNukes = T{ 
		'Silent Storm', 
		'Tenebral Crush', 
		'Palling Salvo', 
		'Searing Tempest', 
		'Thermal Pulse', 
		'Anvil Lightning', 
		'Spectral Floe', 
		'Dark Orb', 
		'Scouring Spate', 
		'Molting Plumage', 
		'Nectarous Deluge', 
		'Entomb',
	},
	BluCures = T{
		'Plenilune Embrace', 
		'Restoral',
		'White Wind',
	},
	BluBuffs = T{
		'Metallic Body',
		'Occultation',
	},
	BluDebuffs = T{
		'Yawn',
		'Soporific',
		'Dream Flower',
		'Blank Gaze',
		'Geist Wall',
		'Feather Tickle',
		'Sheep Song',
		'Chaotic Eye',
		'Water Bomb',
	},
	NinNukes = T{
		'Katon: San',
		'Hyoton: San',
		'Huton: San',
		'Doton: San',
		'Raiton: San',
		'Suiton: San',
	},
	NinDebuffs = T{
		'Kurayami: San',
		'Dokumori: Ni',
		'Jubaku: Ni',
		'Hojo: San',
		'Yurin: Ichi',
	},
	NinBuffs = T{
		'Tonko: Ni',
		'Monomi: Ichi',
		'Migawari: Ichi',
	},
	TH = {
        Head = 'Volte Cap',
	    Body = 'Volte Jupon',
        Hands = 'Volte Bracers',
        Waist = 'Chaac Belt',
        Legs = 'Volte Hose',
        Feet = 'Volte Boots',
    },
	FastCast = {
        Neck = 'Voltsurge Torque',
        Ring1 = 'Prolix Ring',
	},
	BluSkill = {
		Neck = 'Incanter\'s Torque',
		Ring1 = { Name = 'Stikini Ring +1', Augment = 'Blue Magic skill +20' },
        Ring2 = 'Metamor. Ring +1',
		Ear1 = 'Njordr Earring',
		Hands = 'Rawhide Gloves',
        Ammo = 'Sapience Orb',
	},
	Enspell = {
        Ammo = { Name = 'Floestone', Augment = 'Sword enhancement spell damage +40' },
        Head = { Name = 'Pixie Hairpin', Augment = 'Sword enhancement spell damage +40' },
        Neck = { Name = 'Fiend Torque', Augment = 'Sword enhancement spell damage +40' },
        Ear1 = { Name = 'Valor Earring', Augment = 'Sword enhancement spell damage +40' },
        Ear2 = { Name = 'Stm. Earring +1', Augment = 'Sword enhancement spell damage +40' },
        Body = { Name = 'Elvaan Jerkin', Augment = 'Sword enhancement spell damage +40' },
        Hands = { Name = 'Agent Cuffs', Augment = 'Sword enhancement spell damage +40' },
        Ring1 = { Name = 'Balrahn\'s Ring', Augment = 'Sword enhancement spell damage +40' },
        Ring2 = { Name = 'San d\'Orian Ring', Augment = 'Sword enhancement spell damage +40' },
        Back = { Name = 'Wyvern Mantle', Augment = 'Sword enhancement spell damage +40' },
        Waist = { Name = 'Tilt Belt', Augment = 'Sword enhancement spell damage +40' },
        Legs = { Name = 'Agent Pants', Augment = 'Sword enhancement spell damage +40' },
        Feet = { Name = 'Agent Boots', Augment = 'Sword enhancement spell damage +40' },
    },
	Regen = {
        Neck = { Name = 'Twilight Torque', Augment = '"Regen"+80' },
        Ring1 = { Name = 'Defending Ring', Augment = { [1] = '"Refresh"+40', [2] = '"Regen"+40' } },
        Ring2 = { Name = 'Shadow Ring', Augment = { [1] = '"Refresh"+40', [2] = '"Regen"+40' } },
        Back = { Name = 'Shadow Mantle', Augment = '"Regen"+80' },
        Waist = { Name = 'Flume Belt +1', Augment = '"Regen"+80' },
    },
};

return vars;